"""GitHub onboarding provider.

Generates:
  - .github/workflows/ci.yml          (CI pipeline)
  - .github/workflows/release.yml     (release workflow)
  - .github/CODEOWNERS
  - .github/PULL_REQUEST_TEMPLATE.md
  - branch-protection-settings.yaml   (apply via gh CLI instructions)
"""
from __future__ import annotations

import textwrap
from typing import Any, Dict

from .base import BaseProvider, OnboardingResult

# --------------------------------------------------------------------------- #
# Language → CI steps
# --------------------------------------------------------------------------- #
_CI_STEPS: Dict[str, str] = {
    "python": textwrap.dedent("""\
        - uses: actions/setup-python@v5
          with:
            python-version: '3.12'
            cache: pip
        - run: pip install -r requirements.txt
        - run: flake8 .
        - run: pytest --junitxml=reports/junit.xml"""),
    "java": textwrap.dedent("""\
        - uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: '21'
            cache: maven
        - run: mvn --no-transfer-progress verify"""),
    "node": textwrap.dedent("""\
        - uses: actions/setup-node@v4
          with:
            node-version: '20'
            cache: npm
        - run: npm ci
        - run: npm test -- --ci
        - run: npm run build"""),
    "go": textwrap.dedent("""\
        - uses: actions/setup-go@v5
          with:
            go-version: '1.22'
        - run: go vet ./...
        - run: go test -v ./..."""),
}

_DEFAULT_CI_STEPS = "- run: make ci"


def _render_ci_workflow(project: Dict[str, Any], cfg: Dict[str, Any]) -> str:
    lang = project.get("language", "").lower()
    steps = _CI_STEPS.get(lang, _DEFAULT_CI_STEPS)
    default_branch = project.get("default_branch", cfg.get("default_branch", "main"))

    return textwrap.dedent(f"""\
        # CI workflow generated by devsecops-assistant
        name: CI

        on:
          push:
            branches: ["{default_branch}", "develop"]
          pull_request:
            branches: ["{default_branch}"]

        permissions:
          contents: read

        jobs:
          build:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4
        {textwrap.indent(steps, '      ')}

          security-scan:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4
              - uses: aquasecurity/trivy-action@master
                with:
                  scan-type: fs
                  format: table
                  exit-code: '1'
                  severity: CRITICAL,HIGH
    """)


def _render_release_workflow(project: Dict[str, Any], _cfg: Dict[str, Any]) -> str:
    return textwrap.dedent(f"""\
        # Release workflow generated by devsecops-assistant
        name: Release

        on:
          push:
            tags: ['v*']

        permissions:
          contents: write
          packages: write

        jobs:
          release:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4
              - name: Build Docker image
                run: docker build -t ghcr.io/${{{{ github.repository }}}}:${{{{ github.ref_name }}}} .
              - name: Push Docker image
                run: |
                  echo "${{{{ secrets.GITHUB_TOKEN }}}}" | docker login ghcr.io -u ${{{{ github.actor }}}} --password-stdin
                  docker push ghcr.io/${{{{ github.repository }}}}:${{{{ github.ref_name }}}}
              - name: Create GitHub Release
                uses: softprops/action-gh-release@v2
                with:
                  generate_release_notes: true
    """)


def _render_codeowners(project: Dict[str, Any], cfg: Dict[str, Any]) -> str:
    team = project.get("team", cfg.get("default_team", "platform-team"))
    org = cfg.get("org", "my-org")
    return textwrap.dedent(f"""\
        # CODEOWNERS — generated by devsecops-assistant
        # Global owners
        *   @{org}/{team}

        # CI/CD config owners
        .github/   @{org}/{team}
        Jenkinsfile @{org}/{team}
    """)


def _render_pr_template() -> str:
    return textwrap.dedent("""\
        ## Description
        <!-- What does this PR do? -->

        ## Type of change
        - [ ] Bug fix
        - [ ] New feature
        - [ ] Refactoring
        - [ ] Docs / config

        ## Checklist
        - [ ] Tests added / updated
        - [ ] Documentation updated
        - [ ] Security impact considered
        - [ ] Reviewer assigned
    """)


def _render_branch_protection(project: Dict[str, Any], cfg: Dict[str, Any]) -> str:
    repo = project.get("repo_url", "").rstrip(".git").split("/")[-1] or project["name"]
    org = cfg.get("org", "<ORG>")
    default_branch = project.get("default_branch", cfg.get("default_branch", "main"))
    required_checks = cfg.get("required_status_checks", ["build", "security-scan"])
    checks_yaml = "\n".join(f"  - {c}" for c in required_checks)

    return textwrap.dedent(f"""\
        # branch-protection-settings.yaml — generated by devsecops-assistant
        # Apply via GitHub API or gh CLI:
        #
        #   gh api repos/{org}/{repo}/branches/{default_branch}/protection \\
        #     --method PUT --input branch-protection-settings.yaml
        #
        # (requires admin scope on the token)

        repo: {org}/{repo}
        branch: {default_branch}
        required_status_checks:
          strict: true
          contexts:
        {checks_yaml}
        enforce_admins: true
        required_pull_request_reviews:
          required_approving_review_count: 1
          dismiss_stale_reviews: true
          require_code_owner_reviews: true
        restrictions: null
    """)


class GitHubProvider(BaseProvider):
    name = "github"

    def onboard(self) -> OnboardingResult:
        result = OnboardingResult(self.name)

        if not self.project.get("name"):
            result.add_error("project.name is required for GitHub onboarding")
            return result

        result.add_file(".github/workflows/ci.yml",
                        _render_ci_workflow(self.project, self.tool_cfg))
        result.add_file(".github/workflows/release.yml",
                        _render_release_workflow(self.project, self.tool_cfg))
        result.add_file(".github/CODEOWNERS",
                        _render_codeowners(self.project, self.tool_cfg))
        result.add_file(".github/PULL_REQUEST_TEMPLATE.md",
                        _render_pr_template())
        result.add_file("branch-protection-settings.yaml",
                        _render_branch_protection(self.project, self.tool_cfg))

        org = self.tool_cfg.get("org", "<ORG>")
        repo = self.project.get("repo_url", "").split("/")[-1].rstrip(".git") or self.project["name"]

        result.add_message(
            f"GitHub artefacts generated.\n"
            f"  1. Copy .github/ directory to your repository root.\n"
            f"  2. Apply branch protection:\n"
            f"     gh api repos/{org}/{repo}/branches/{project_default_branch(self.project, self.tool_cfg)}/protection \\\n"
            f"       --method PUT --input github/branch-protection-settings.yaml\n"
            f"  3. Ensure GITHUB_TOKEN has 'packages: write' for Docker image pushes."
        )
        return result


def project_default_branch(project: Dict[str, Any], cfg: Dict[str, Any]) -> str:
    return project.get("default_branch", cfg.get("default_branch", "main"))
