"""Harness onboarding provider.

Generates:
  - harness/pipeline.yaml       (CI/CD pipeline)
  - harness/service.yaml        (service definition)
  - harness/environment.yaml    (environment with infrastructure)
  - harness/input-set.yaml      (runtime input set)
"""
from __future__ import annotations

import textwrap
from typing import Any, Dict

from .base import BaseProvider, OnboardingResult


def _render_pipeline(project: Dict[str, Any], cfg: Dict[str, Any]) -> str:
    org = cfg.get("org_id", "default")
    project_id = cfg.get("project_id", project["name"].lower().replace("-", "_"))
    account = cfg.get("account_id", "<ACCOUNT_ID>")
    connector = cfg.get("docker_connector", "docker_hub")
    repo_connector = cfg.get("repo_connector", "github_connector")
    name = project["name"]
    lang = project.get("language", "python").lower()

    build_step = {
        "python": f"pip install -r requirements.txt && pytest",
        "java": "mvn clean verify",
        "node": "npm ci && npm test",
        "go": "go test ./...",
    }.get(lang, "make test")

    return textwrap.dedent(f"""\
        # harness/pipeline.yaml — generated by devsecops-assistant
        pipeline:
          name: {name}-pipeline
          identifier: {name.replace('-', '_')}_pipeline
          projectIdentifier: {project_id}
          orgIdentifier: {org}
          tags:
            managed-by: devsecops-assistant
          stages:
            - stage:
                name: Build & Test
                identifier: build_test
                type: CI
                spec:
                  cloneCodebase: true
                  platform:
                    os: Linux
                    arch: Amd64
                  runtime:
                    type: Cloud
                    spec: {{}}
                  execution:
                    steps:
                      - step:
                          type: Run
                          name: Build and Test
                          identifier: build_and_test
                          spec:
                            connectorRef: {repo_connector}
                            image: {_ci_image(lang)}
                            command: |
                              {build_step}
                      - step:
                          type: Security
                          name: Aqua Trivy Scan
                          identifier: trivy_scan
                          spec:
                            privileged: true
                            settings:
                              product_name: aqua-trivy
                              product_config_name: aqua-trivy
                              target_type: repository
                              target_name: {name}
                              target_variant: <+codebase.branch>
                            imagePullPolicy: Always

            - stage:
                name: Build & Push Image
                identifier: build_push_image
                type: CI
                spec:
                  cloneCodebase: true
                  platform:
                    os: Linux
                    arch: Amd64
                  runtime:
                    type: Cloud
                    spec: {{}}
                  execution:
                    steps:
                      - step:
                          type: BuildAndPushDockerRegistry
                          name: Push Docker Image
                          identifier: push_docker_image
                          spec:
                            connectorRef: {connector}
                            repo: <+pipeline.variables.docker_repo>
                            tags:
                              - <+pipeline.sequenceId>
                              - latest

            - stage:
                name: Deploy
                identifier: deploy
                type: Deployment
                spec:
                  deploymentType: Kubernetes
                  service:
                    serviceRef: {name.replace('-', '_')}_service
                  environment:
                    environmentRef: <+input>
                    deployToAll: false
                    infrastructureDefinitions:
                      - identifier: <+input>
                  execution:
                    steps:
                      - step:
                          type: K8sRollingDeploy
                          name: Rolling Deploy
                          identifier: rolling_deploy
                          spec:
                            skipDryRun: false
                    rollbackSteps:
                      - step:
                          type: K8sRollingRollback
                          name: Rolling Rollback
                          identifier: rolling_rollback
                          spec: {{}}

          variables:
            - name: docker_repo
              type: String
              description: Docker image repository
              required: true
              value: <+input>

          properties:
            ci:
              codebase:
                connectorRef: {repo_connector}
                repoName: {project.get('repo_url', name).split('/')[-1].rstrip('.git')}
                build: <+input>
    """)


def _ci_image(lang: str) -> str:
    return {
        "python": "python:3.12-slim",
        "java": "maven:3.9-eclipse-temurin-21",
        "node": "node:20-alpine",
        "go": "golang:1.22-alpine",
    }.get(lang, "ubuntu:22.04")


def _render_service(project: Dict[str, Any], cfg: Dict[str, Any]) -> str:
    org = cfg.get("org_id", "default")
    project_id = cfg.get("project_id", project["name"].lower().replace("-", "_"))
    name = project["name"]
    connector = cfg.get("docker_connector", "docker_hub")

    return textwrap.dedent(f"""\
        # harness/service.yaml — generated by devsecops-assistant
        service:
          name: {name}
          identifier: {name.replace('-', '_')}_service
          projectIdentifier: {project_id}
          orgIdentifier: {org}
          description: "{project.get('description', name)}"
          tags:
            managed-by: devsecops-assistant
          serviceDefinition:
            type: Kubernetes
            spec:
              manifests:
                - manifest:
                    identifier: k8s_manifest
                    type: K8sManifest
                    spec:
                      store:
                        type: Github
                        spec:
                          connectorRef: github_connector
                          gitFetchType: Branch
                          paths:
                            - k8s/
                          branch: main
                      valuesPaths:
                        - k8s/values.yaml
              artifacts:
                primary:
                  primaryArtifactRef: <+input>
                  sources:
                    - spec:
                        connectorRef: {connector}
                        imagePath: <+pipeline.variables.docker_repo>
                        tag: <+pipeline.sequenceId>
                      identifier: primary_artifact
                      type: DockerRegistry
    """)


def _render_environment(project: Dict[str, Any], cfg: Dict[str, Any]) -> str:
    org = cfg.get("org_id", "default")
    project_id = cfg.get("project_id", project["name"].lower().replace("-", "_"))
    name = project["name"]
    cluster_connector = cfg.get("k8s_connector", "k8s_prod_cluster")
    namespace = cfg.get("namespace", name.lower())

    return textwrap.dedent(f"""\
        # harness/environment.yaml — generated by devsecops-assistant
        environment:
          name: production
          identifier: production
          projectIdentifier: {project_id}
          orgIdentifier: {org}
          type: Production
          tags:
            managed-by: devsecops-assistant
          infrastructureDefinitions:
            - infrastructure:
                name: k8s-production
                identifier: k8s_production
                type: KubernetesDirect
                spec:
                  connectorRef: {cluster_connector}
                  namespace: {namespace}
                  releaseName: release-<+INFRA_KEY>
    """)


def _render_input_set(project: Dict[str, Any], cfg: Dict[str, Any]) -> str:
    org = cfg.get("org_id", "default")
    project_id = cfg.get("project_id", project["name"].lower().replace("-", "_"))
    name = project["name"]
    docker_repo = cfg.get("docker_image_repo", f"myorg/{name}")

    return textwrap.dedent(f"""\
        # harness/input-set.yaml — generated by devsecops-assistant
        # Use this input set to pre-fill pipeline runtime inputs for CI runs
        inputSet:
          name: default-inputs
          identifier: default_inputs
          projectIdentifier: {project_id}
          orgIdentifier: {org}
          pipeline:
            identifier: {name.replace('-', '_')}_pipeline
            properties:
              ci:
                codebase:
                  build:
                    type: branch
                    spec:
                      branch: main
            variables:
              - name: docker_repo
                type: String
                value: {docker_repo}
            stages:
              - stage:
                  identifier: deploy
                  type: Deployment
                  spec:
                    environment:
                      environmentRef: production
                      infrastructureDefinitions:
                        - identifier: k8s_production
    """)


class HarnessProvider(BaseProvider):
    name = "harness"

    def onboard(self) -> OnboardingResult:
        result = OnboardingResult(self.name)

        if not self.project.get("name"):
            result.add_error("project.name is required for Harness onboarding")
            return result

        result.add_file("harness/pipeline.yaml",
                        _render_pipeline(self.project, self.tool_cfg))
        result.add_file("harness/service.yaml",
                        _render_service(self.project, self.tool_cfg))
        result.add_file("harness/environment.yaml",
                        _render_environment(self.project, self.tool_cfg))
        result.add_file("harness/input-set.yaml",
                        _render_input_set(self.project, self.tool_cfg))

        account = self.tool_cfg.get("account_id", "<ACCOUNT_ID>")
        org = self.tool_cfg.get("org_id", "default")
        project_id = self.tool_cfg.get(
            "project_id", self.project["name"].lower().replace("-", "_")
        )

        result.add_message(
            f"Harness artefacts generated.\n"
            f"  Apply via Harness CLI (harness-cli):\n"
            f"    harness-cli pipeline apply   --file harness/pipeline.yaml\n"
            f"    harness-cli service apply    --file harness/service.yaml\n"
            f"    harness-cli environment apply --file harness/environment.yaml\n"
            f"    harness-cli input-set apply  --file harness/input-set.yaml\n"
            f"  Or import via the Harness UI:\n"
            f"    Account: {account}  Org: {org}  Project: {project_id}\n"
            f"  Required connectors: github_connector, {self.tool_cfg.get('docker_connector','docker_hub')}, "
            f"{self.tool_cfg.get('k8s_connector','k8s_prod_cluster')}"
        )
        return result
