"""Jenkins onboarding provider.

Generates:
  - Jenkinsfile (declarative pipeline)
  - jenkins-job.xml  (importable via jenkins-cli or Job DSL)
"""
from __future__ import annotations

import textwrap
from typing import Any, Dict

from .base import BaseProvider, OnboardingResult

# --------------------------------------------------------------------------- #
# Language → build stage snippets
# --------------------------------------------------------------------------- #
_BUILD_STAGES: Dict[str, str] = {
    "python": textwrap.dedent("""\
        stage('Install') {
            steps { sh 'pip install -r requirements.txt' }
        }
        stage('Test') {
            steps { sh 'pytest --junitxml=reports/junit.xml' }
        }
        stage('Lint') {
            steps { sh 'flake8 .' }
        }"""),
    "java": textwrap.dedent("""\
        stage('Build') {
            steps { sh 'mvn clean package -DskipTests' }
        }
        stage('Test') {
            steps { sh 'mvn test' }
        }"""),
    "node": textwrap.dedent("""\
        stage('Install') {
            steps { sh 'npm ci' }
        }
        stage('Test') {
            steps { sh 'npm test -- --ci' }
        }
        stage('Build') {
            steps { sh 'npm run build' }
        }"""),
    "go": textwrap.dedent("""\
        stage('Build') {
            steps { sh 'go build ./...' }
        }
        stage('Test') {
            steps { sh 'go test ./...' }
        }"""),
}

_DEFAULT_BUILD_STAGES = textwrap.dedent("""\
    stage('Build') {
        steps { sh 'make build' }
    }
    stage('Test') {
        steps { sh 'make test' }
    }""")


def _render_jenkinsfile(project: Dict[str, Any], cfg: Dict[str, Any]) -> str:
    lang = project.get("language", "").lower()
    build_stages = _BUILD_STAGES.get(lang, _DEFAULT_BUILD_STAGES)
    agent_label = cfg.get("agent_label", "any")
    branch_pattern = cfg.get("branch_pattern", "main|develop|feature/.*")
    docker_image = cfg.get("docker_image", "")

    agent_block = (
        f"agent {{ docker {{ image '{docker_image}' }} }}"
        if docker_image
        else f"agent {{ label '{agent_label}' }}"
    )

    return textwrap.dedent(f"""\
        // Jenkinsfile generated by devsecops-assistant
        // Project: {project['name']}
        pipeline {{
            {agent_block}

            triggers {{
                pollSCM('H/5 * * * *')
            }}

            options {{
                buildDiscarder(logRotator(numToKeepStr: '20'))
                timestamps()
                timeout(time: 30, unit: 'MINUTES')
            }}

            stages {{
        {textwrap.indent(build_stages, '        ')}

                stage('Docker Build & Push') {{
                    when {{ branch pattern: '{branch_pattern}', comparator: 'REGEXP' }}
                    steps {{
                        script {{
                            def img = docker.build("{project['name']}:${{env.BUILD_NUMBER}}")
                            docker.withRegistry('', 'docker-credentials') {{
                                img.push()
                                img.push('latest')
                            }}
                        }}
                    }}
                }}
            }}

            post {{
                always {{
                    junit allowEmptyResults: true, testResults: 'reports/**/*.xml'
                    cleanWs()
                }}
                failure {{
                    emailext subject: "FAILED: ${{env.JOB_NAME}} #${{env.BUILD_NUMBER}}",
                             body: "See ${{env.BUILD_URL}}",
                             recipientProviders: [[$class: 'RequesterRecipientProvider']]
                }}
            }}
        }}
    """)


def _render_job_xml(project: Dict[str, Any], cfg: Dict[str, Any]) -> str:
    repo_url = project.get("repo_url", "https://github.com/org/repo.git")
    default_branch = project.get("default_branch", "main")
    folder = cfg.get("folder", "")
    description = project.get("description", project["name"])

    return textwrap.dedent(f"""\
        <?xml version='1.1' encoding='UTF-8'?>
        <!-- jenkins-job.xml generated by devsecops-assistant -->
        <!-- Import via: java -jar jenkins-cli.jar -s <JENKINS_URL> create-job {folder}/{project['name']} < jenkins-job.xml -->
        <flow-definition plugin="workflow-job">
          <description>{description}</description>
          <keepDependencies>false</keepDependencies>
          <properties/>
          <definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition"
                       plugin="workflow-cps">
            <scm class="hudson.plugins.git.GitSCM" plugin="git">
              <configVersion>2</configVersion>
              <userRemoteConfigs>
                <hudson.plugins.git.UserRemoteConfig>
                  <url>{repo_url}</url>
                  <credentialsId>git-credentials</credentialsId>
                </hudson.plugins.git.UserRemoteConfig>
              </userRemoteConfigs>
              <branches>
                <hudson.plugins.git.BranchSpec>
                  <name>*/{default_branch}</name>
                </hudson.plugins.git.BranchSpec>
              </branches>
              <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
              <submoduleCfg class="empty-list"/>
              <extensions/>
            </scm>
            <scriptPath>Jenkinsfile</scriptPath>
            <lightweight>true</lightweight>
          </definition>
          <triggers/>
          <disabled>false</disabled>
        </flow-definition>
    """)


class JenkinsProvider(BaseProvider):
    name = "jenkins"

    def onboard(self) -> OnboardingResult:
        result = OnboardingResult(self.name)

        if not self.project.get("name"):
            result.add_error("project.name is required for Jenkins onboarding")
            return result

        result.add_file("Jenkinsfile", _render_jenkinsfile(self.project, self.tool_cfg))
        result.add_file("jenkins-job.xml", _render_job_xml(self.project, self.tool_cfg))

        jenkins_url = self.tool_cfg.get("url", "<JENKINS_URL>")
        folder = self.tool_cfg.get("folder", "")
        job_path = f"{folder}/{self.project['name']}" if folder else self.project["name"]

        result.add_message(
            f"Jenkins artefacts generated.\n"
            f"  1. Copy Jenkinsfile to the root of your repository.\n"
            f"  2. Import the pipeline job:\n"
            f"     java -jar jenkins-cli.jar -s {jenkins_url} create-job {job_path} < jenkins-job.xml\n"
            f"  3. Ensure the following credentials exist in Jenkins:\n"
            f"     - 'git-credentials'   (SCM access)\n"
            f"     - 'docker-credentials' (Docker registry push)"
        )
        return result
